// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6ZPCgR20tqAsWyzP3TBgCW_Z4wLxNqs',
    appId: '1:1096040991582:android:5d8e021386733b9c339dcf',
    messagingSenderId: '1096040991582',
    projectId: 'cric-4c410',
    storageBucket: 'cric-4c410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_FL9bigUjIRvd5ayaRlcQX2WdALc3vI',
    appId: '1:1096040991582:ios:2c58dfc185eb6d9b339dcf',
    messagingSenderId: '1096040991582',
    projectId: 'cric-4c410',
    storageBucket: 'cric-4c410.appspot.com',
    iosBundleId: 'com.example.devotionals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw_FL9bigUjIRvd5ayaRlcQX2WdALc3vI',
    appId: '1:1096040991582:ios:c356ae94e5083888339dcf',
    messagingSenderId: '1096040991582',
    projectId: 'cric-4c410',
    storageBucket: 'cric-4c410.appspot.com',
    iosBundleId: 'com.example.devotionals.RunnerTests',
  );
}
